# Generated by Django 4.1.1 on 2022-09-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('extra_data_json', models.CharField(blank=True, max_length=2000, null=True)),
                ('icon', models.CharField(blank=True, default='las la-question-circle', max_length=50, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
                ('unique_key', models.CharField(max_length=250, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crawler.job')),
                ('site_conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crawler.siteconf')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='site_conf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='crawler.siteconf'),
        ),
        migrations.CreateModel(
            name='ExtraTaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.CharField(blank=True, max_length=2000, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_data', to='crawler.task')),
            ],
        ),
    ]
