# Generated by Django 4.1.1 on 2023-03-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0002_alter_task_unique_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="url",
            field=models.URLField(blank=True, max_length=2500, null=True),
        ),
    ]
