# Generated by Django 4.1.1 on 2022-09-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
