# Generated by Django 4.1.1 on 2023-12-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_alter_task_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconf',
            name='ns_flag',
            field=models.BooleanField(default=False),
        ),
    ]
