# Generated by Django 4.1.1 on 2022-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_task_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
