# Generated by Django 4.1.1 on 2022-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_task_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
