# Generated by Django 4.1.1 on 2022-09-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_job_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconf',
            name='scraper_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
