# Generated by Django 4.1.1 on 2022-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_alter_configvalues_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR'), ('NO-TASK', 'NO-TASK')], default='NEW', max_length=20),
        ),
    ]
