# Generated by Django 4.1.1 on 2022-09-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_job_elapsed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='elapsed_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
