# Generated by Django 4.1.1 on 2023-02-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0013_category_siteconf_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
