# Generated by Django 4.1.1 on 2023-02-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0014_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconf',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_confs', to='crawler.category'),
        ),
    ]
